### ISSUE TITLE
array crashes

### ISSUE THREAD

**Issue by Nodnarb12500** [Crowlang/crow#61]
i have caused a crash with 2 array tests
```
(defvar my-array (array 1 2 3 4 5))
(array-set my-array 3 "hello")
```
fish: Job 1, '~/Documents/GIT/crow/crow crowD…' terminated by signal SIGSEGV (Address boundary error)

```
(defvar my-array (array 1 2 3 4 5))
(prinln (array-get my-array 20))
```
fish: Job 1, '~/Documents/GIT/crow/crow crowD…' terminated by signal SIGSEGV (Address boundary error)

**Comment by Bravotic** [comment]
Most likely a garbage collector issue, will investigate.

**Comment by Bravotic** [comment]
This is fixed with the commit above. As for the crash from array-get, array-get on an index larger than the array has causes "Undefined" to be returned. Since printing this was broken (see issue #64), that is most likely the reason that it crashed on you. Closing this issue for now, feel free to reopen if the crashes persist.
