### ISSUE TITLE
defined function cant be found when called

### ISSUE THREAD

**Issue by Nodnarb12500** [Crowlang/crow#65]
Ive found another function that has a similar issue to #56 but does not have comments in it.

```
(defvar mylib (load-library "mylib.so"))
(defvar myfunc (get-function mylib "my_func"))

(myfunc 10)
```
Function '(myfunc 10)' is not defined

**Comment by Bravotic** [comment]
This is because mylib.so does not exist, or the function within it does not exist. These functions are for loading external functions out of a c library, they return undefined when not found, therefore this is working as intended. Now if you __are__ loading a library and the function __does__ exist, then this is a problem.
