### ISSUE TITLE
(= var1 var2) not a boolean

### ISSUE THREAD

**Issue by Nodnarb12500** [Crowlang/crow#68]
```
(defvar x 0)

(loop (if (!= x 5)
          (set x (+ x 1))
          (println x)
          (if (= x 5)
              (break "found five")
          )

))
```
```
5
Error: not boolean
```
the output is spammed and doesnt stop

attempting to force x to be a number using (number x) doesnt change anything

**Comment by Nodnarb12500** [comment]
i think (= var1 var2) it just broken
running all the examples for = from the crow docs in REPL
```
% (println (= 5 5))
true
"true"
% (println (= 5 "5"))
Error: A is not the same type as B
Undefined
"Undefined"
% (println (= "hello" "world"))
false
"false"
% (println (= "hello" "hello"))
true
"true"
% (println (= true true))
Error: cannot do operation with that
Undefined
"Undefined"
% (println (= false false))
Error: cannot do operation with that
Undefined
"Undefined"
```

**Comment by Bravotic** [comment]
This looks to be a typo in the program. I am working on better error messages so that should eventually help to solve this, but it looks like your if statement is written wrong. If you wish to have multiple lines of code in an if clause, consider using `when` which looks like `(when condition expression...)`, if can only take one expression after the condition. The error "not boolean" is coming from the if statement complaining that some code it is trying to run isn't evaluating to a boolean. Closing this unless you can find another issue with this code that isn't syntax related.

**Comment by Nodnarb12500** [comment]
okay i guess, i can see the first program being incorrect but the examples in the docs dont work in REPL
